[tool.poetry]
name = "senselab"
version = "0.0.1"
description = "Senselab is a Python package that simplifies building pipelines for speech and voice analysis."
authors = [
  "Fabio Catania <fabiocat@mit.edu>",
  "Satra Ghosh <satra@mit.edu>"
]
maintainers = [
  "Fabio Catania <fabiocat@mit.edu>",
  "Satra Ghosh <satra@mit.edu>"
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/sensein/senselab"
repository = "https://github.com/sensein/senselab"
documentation = "https://sensein.github.io/senselab"
keywords = ["voice", "speech", "audio"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent"
]
packages = [{include = "senselab", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
jsonschema = "^4.21.1"
datasets = "^2.19.2"
torch = "^2.2.2"
torchvision = "^0.17.2"
torchaudio = "^2.2.2"
transformers = "^4.39.3"
ffmpeg-python = "^0.2.0"
ipykernel = "^6.29.4"
pydra = "^0.23"
pydantic = "^2.7.3"
accelerate = "^0.29.3"
huggingface-hub = "^0.23.3"
praat-parselmouth = "^0.4.3"
audiomentations = "^0.35.0"
torch-audiomentations = "^0.11.1"
sentence-transformers = "^2.7.0"
jiwer = "^3.0.4"
speechbrain = "^1.0.0"
pyannote-audio = "^3.2.0"
pycountry = "^24.6.1"
opensmile = "^2.5.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-mock = "^3.14.0"
mypy = "^1.9.0"
pre-commit = "^3.7.0"
pytest-cov = "^5.0.0"
ruff = "^0.3.4"
codespell = "^2.3.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
pdoc = "^14.4.0"

[tool.poetry.scripts]
senselab-cli = "senselab.cli:main"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
testpaths = [
  "src/tests"
]

[tool.mypy]
ignore_missing_imports = true
plugins = [
  "pydantic.mypy"
]

[tool.ruff]
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv"
]
line-length = 120
indent-width = 4
src = ["src"]
target-version = "py310"

[tool.ruff.lint]
select = ["ANN", "D", "E", "F", "I"]
ignore = [
  "ANN101",  # self should not be annotated.
  "ANN102"  # cls should not be annotated.
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"src/tests/**/*.py" = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
pattern = "default-unprefixed"

[tool.codespell]
skip = [
  "poetry.lock",
  "docs_style/pdoc-theme/syntax-highlighting.css"
]
ignore-words-list = ["senselab", "nd", "astroid", "wil"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
